Draft: Fixes Filelogger logging after erasing all files
Qase/swift-logger pull request #15
Opened 2022-12-21 17:13 UTC by David2XN

Fixes Filelogger logging after erasing all files.

Added following logic to deleteAllLogFiles method:
- Clears invalid file handle
- Resets current log number to zero

2022-12-22 10:40 UTC, troupmar requested changes

2022-12-22 10:40 UTC, troupmar commented on Tests/LoggerTests/Loggers/FileLoggerTests.swift
> +    func test_delete_log_files() throws {
Maybe more descriptive name for the function? Something like `test_deleting_log_files_resets_the_logger_configuration`...

2022-12-22 10:46 UTC, troupmar approved these changes

2022-12-27 19:43 UTC, EllaGogo approved these changes

2022-12-30 10:30 UTC, merged