Refactor - deleted syncSerial and syncConcurrent
Qase/swift-logger pull request #17
Opened 2023-05-29 08:08 UTC by yOoZZyOzzbourne

After debating about concurrency modes, we agreed to these changes. Only mode left should be `asyncSerial`, main reason is that it does not block the `main queue` like the other two options.
So my refactor work deletes the two modes and leaves only `asyncSerial`.

I left it like an enum, so that it doesnt break all the projects and if the project is already using asyncSerial (like it should), fix is not needed.

Readme + comments fixed.

2023-05-29 15:30 UTC, troupmar requested changes

2023-05-29 15:30 UTC, troupmar commented on README.md
>  Logging task is dispatched asynchronously on a custom serial queue, where all loggers perform their tasks serially one by one.
Chtelo by se to bud uplne zbavit tech logging modes nebo aspon tyhle README casti a nebo napsat, ze zadny dalsi mody zatim nejsou podporovany. Takhle je zavadejici, ze je tu vycet modu ale ve vysledku je jen jeden. Chapu, zes to tak nechal kvuli zpetny kompatibilite ale mozna bych se s tim nesral a kompletne ty logging modes odstranil se vsim vsudy...

2023-05-31 15:57 UTC, troupmar requested changes

2023-05-31 15:57 UTC, troupmar commented on Sources/Logger/LoggerManager.swift
> +public extension DispatchQueue {
Premejslim, jestli musi bejt ta instance `public`, podle me by ji mel videt jen ten `LoggerManager`, takze `private` max `fileprivate`.

2023-05-31 15:57 UTC, troupmar commented on README.md
> +`LoggerManager` has its own style of executing tasks. It's done in form of `asyncSerial` style, that works on background thread without disrupting the main thread.
Nemas cleny, `in the form of` a `works on the background thread`. Navic tam mas jen pulku pribehu, a to `async`. Napsal bych tam jeste vetu k ty druhy pulce pribehu, tj. `serial`. Logging into individual loggers is done in serial fashion, thus one by one. Nebo neco takovyho...

2023-05-31 17:14 UTC, troupmar approved these changes

2023-05-31 18:00 UTC, EllaGogo requested changes

2023-05-31 18:00 UTC, EllaGogo commented on README.md
> +`LoggerManager` has its own style of executing tasks. It's done in the form of `asyncSerial` style, that works on the background thread without disrupting the main thread.
Ja by som zmenila tuto sekci. `asyncSerial` uz v kodu realne neni, takze mi nedava smysl to spominat v readme. Muj navrh je tam mit jenom tohle:

### Logging execution
`LoggerManager` handles execution of logging tasks in an asynchronous serial manner. Each logging task is dispatched asynchronously on a custom serial background queue, where all loggers perform their tasks serially one by one.

2023-05-31 18:21 UTC, yOoZZyOzzbourne commented on README.md
> +`LoggerManager` has its own style of executing tasks. It's done in the form of `asyncSerial` style, that works on the background thread without disrupting the main thread.
chtěl jsem to tam nechat i s tím obrázkem ale asi to dává smysl to dát pryč

2023-05-31 18:23 UTC, EllaGogo commented on README.md
> +`LoggerManager` has its own style of executing tasks. It's done in the form of `asyncSerial` style, that works on the background thread without disrupting the main thread.
obrazek tam muze zustat klidne

2023-05-31 19:02 UTC, EllaGogo approved these changes

2023-05-31 19:03 UTC, merged