Fix/multithreading bug
Qase/swift-logger pull request #18
Opened 2023-06-09 22:35 UTC by yOoZZyOzzbourne

Issue with two asynchronous actions taking place at the same time. More precisely `Logging` and `DeletingAllLogs` in FileLogger. 

One way of fixing this issue is to do the logging and deleting from `LoggerManager`, which is running on his own serial queue.

Second option ( _the one we went with_ ) is to add new `fileAccessQueue` to the `FileLogger` itself - basically injectable queue thats serial by default. And the two tasks - `Logging` and `Deleting` are running on this queue, so it waits and does tasks one by one and not two of them at the same time. The rest is left as it was, no changes to the functionality of the logger were made. 

One issue is there with tests. Trying to test something that doesnt happen everytime is difficult so we added test that runs `100x log` and `50x delete` both on different `global queues`. In this way we can try and run the test hundrets of times ( _thats the go-to method_ )

2023-06-13 17:04 UTC, troupmar approved these changes

2023-06-13 18:21 UTC, EllaGogo requested changes

2023-06-13 18:21 UTC, EllaGogo commented on Sources/Logger/Loggers/FileLogger/FileAccessExecutor.swift
> +// FileLogger is used to execute logging (writing to a file) and deletion (deleting files) on the same queue, so no race conditions can appear.
Asi nie `FileLogger` ale `FileAccessExecutor`

2023-06-13 18:21 UTC, EllaGogo commented on Sources/Logger/Loggers/FileLogger/FileLogger.swift
>      public func deleteAllLogFiles() throws {
`throws` uz neni potreba

2023-06-13 18:21 UTC, EllaGogo commented on Tests/LoggerTests/Loggers/FileLoggerTests.swift
> +    func test_loggerManager_multithreading_delete_and_log_simultaneously() throws {
`test_fileLogger_...`

2023-06-14 10:01 UTC, EllaGogo approved these changes

2023-06-14 10:20 UTC, merged