feature: unified logging
Qase/swift-logger pull request #20
Opened 2023-07-14 10:36 UTC by Finemas

- Unify the logging level with Apple's logging system.
- Replace SystemLogger and ConsoleLogger with UnifiedLogger, utilizing Apple's logger.
- Add an option to UnifiedLogger to retrieve logs from the current app run. It could potentially replace FileLogger in the future, but currently, you can only obtain logs from the app's current run. Therefore, it is not possible to retrieve logs after the app has crashed or been killed.

2023-07-19 13:58 UTC, troupmar requested changes

2023-07-19 13:58 UTC, troupmar commented on Sources/Logger/Loggers/UnifiedLogger/UnifiedLogger.swift
> +public class UnifiedLogger: Logging {
Ja bych to asi nejak prejmenoval, treba `NativeLogger`? Tohle mi prijde takovy nejednoznacny...

2023-07-20 12:02 UTC, Finemas commented on Sources/Logger/Loggers/UnifiedLogger/UnifiedLogger.swift
> +public class UnifiedLogger: Logging {
Mě jen napadlo UnifiedLogger, jakože spojení `ConsoleLogger` a `SystemLogger`, ale `NativeLogger` je lepší název.

2023-07-20 12:03 UTC, Finemas commented on Sources/Logger/Loggers/UnifiedLogger/UnifiedLogger.swift
> +public class UnifiedLogger: Logging {
Opraveno

2023-07-20 18:54 UTC, troupmar approved these changes

2023-07-21 13:17 UTC, David2XN approved these changes

2023-07-21 15:10 UTC, merged